#
# Jenkins Docker Compose file for Open DevOps Pipeline
#
# VERSION : 1.0
#
version: '2'

services:
  jenkins:
    image: devopsopen/docker-ci-jenkins:alpine
    ports:
      - "50000:50000"
      - "8080:8080"
    env_file:
      - jenkins-master.env
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true 
                  -Djenkins.install.runSetupWizard=false 
                  -Dhttp.proxyHost=${http_proxy_host} 
                  -Dhttp.proxyPort=${http_proxy_port} 
                  -Dhttps.proxyHost=${https_proxy_host} 
                  -Dhttps.proxyPort=${https_proxy_port}
                  -Duser.timezone=Asia/Shanghai
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    restart: never
    volumes:
      - /var/jenkins_home
